apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: dev
spec:
  limits:
  - default:
      cpu: 150m
      memory: 512Mi      
    defaultRequest:
      cpu: 150m
      memory: 256Mi      
    type: Container
