apiVersion: v1
kind: Service
metadata:
  name: restful-web-service-svcnp
  namespace: dev  
spec:
  type: NodePort
  selector:
    run: restful-web-service
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 31001
