apiVersion: v1
kind: Service
metadata:
  name: tomcat-redis-new-svcnp
  namespace: dev  
spec:
  type: NodePort
  selector:
    run: tomcat-redis-new
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30112
