apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: wildfly-redis-new
  name: wildfly-redis-new
spec:
  replicas: 1
  selector:
    matchLabels:
      run: wildfly-redis-new
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: wildfly-redis-new
    spec:
      containers:
      - image: brandon9999/wildfly18jdk8:latest
        name: wildfly-redis-new
        volumeMounts:
        - mountPath: /opt/jboss/wildfly/bin
          name: nfs-volume01
        - mountPath: /opt/jboss/wildfly/tmp
          name: nfs-volume02
        ports:
        - containerPort: 8080
        resources: {}
      volumes:
      - name: nfs-volume01
        nfs:
          server: 192.168.35.210
          path: /home/nfs/wildfly18_redis/bin
          readOnly: false
      - name: nfs-volume02
        nfs:
          server: 192.168.35.210
          path: /home/nfs/wildfly18_redis/tmp
          readOnly: false  
status: {}
